pr 요청 _ 하림
cleancode-practice-study/java-ladder pull request #1
Opened 2022-04-18 19:13 UTC by gkfla668

(test 코드까지 작성해서 pr 요청 하려했는데 지금 껏 해오던 것처럼 하려는데 계속 오류가 ㅜㅜ)

아직 코드 길이, else문, 들여쓰기 등 수정할 게 많지만... 중간 피드백을 받고자 일단 구현은 다 해서 pr 요청 해봅니다! 

게임결과 생성하는 메서드에서 저 많은 if-else문........... 어떻게 수정해야할까요 😅 다 따로따로 분리해야할까요??
첫 pr 피드백 부탁드립니다 바쁘신데 감사해요!!! ☺️

2022-04-19 14:39 UTC, ghost requested changes
잘했는데? 이제 구조를 잘 설계할줄 아는것 같아! 👍 
복잡한 로직만 리팩토링하면 더 좋아질꺼야

2022-04-19 14:39 UTC, gch01410 commented on src/main/java/model/Line.java
> +    public static final int BOUND = 2;
상수와 인스턴스 변수사이에 줄바꿈해서 구분을 해주는게 가독성이 좋아!

2022-04-19 14:39 UTC, ghost commented on src/main/java/model/Ladder.java
> +    public List<Line> getLadder() {
매서드 선언순서 규칙을 지켜줘!

2022-04-19 14:39 UTC, gch01410 commented on src/main/java/model/Ladder.java
> +    private List<Line> getLines(int width, int height) {
이 메서드는 Line 객체를 생성해서 반환하고 있네!
적절한 메서드명으로 변경해보자!
보통 get-메서드는 단순히 값을 꺼낼때 사용해

2022-04-19 14:39 UTC, gch01410 commented on src/main/java/model/Line.java
> +            count++;
Random 객체에 nextBoolean 이라는 메서드를 사용할 수 있어보여

2022-04-19 14:39 UTC, gch01410 commented on src/main/java/model/Ladder.java
> +        return count;
무슨일이 있더라도 java에서 배열보다는 java collection(List, Set, Map)을 사용해줘!
배열의 기능은 모두 갖고있으면서도 추가 기능들이 많아서 값들을 관리하기 더 편해!

그리고 if문 블록안에 한줄만 있으면 중괄호`{}`를 생략할 수 있는데 왠만하면 생략하지 않고 중괄호를 사용해줘!
if문안의 로직에 대한 가독성이 더 좋아져

2022-04-19 14:39 UTC, gch01410 commented on src/main/java/model/Ladder.java
> +        }
do while문을 사용할 수 있어보여

2022-04-19 14:39 UTC, gch01410 commented on src/main/java/model/Players.java
> +        Collections.addAll(player, names);
👍

2022-04-19 14:39 UTC, gch01410 commented on src/main/java/model/GameResult.java
> +    }
GamResult객체가 GameResultCreator 객체를 반드시 필드로 갖고 있어야할까?
클래스 이름만 보면 게임결과를 구하는 객체가 아니라 게임결과를 구해서 갖고 있는 객체일 것 같아!

2022-04-19 14:39 UTC, gch01410 commented on src/main/java/model/GameResultCreator.java
> +        }
ㅎㅎ..
차근차근 리팩토링해보자!

우선 중복로직을 제거해볼까?
1. height를 1씩 증가시키는 로직은 어떤 분기문을 타든지 항상 실행되고 있어!
2. Boolean 리스트를 반복해서 가져오고 있어!

중복로직 제거한 후에 메서드 분리라던지,, 리팩토링을 조금 더 해보자!

2022-04-19 14:39 UTC, gch01410 commented on src/main/java/view/OutputView.java
> +        Map<String, String> results = gameResult.getGameResult();
View영역에서 도메인 영역으로 요청해서 게임결과를 구하고 있는것 아닐까?
View영역은 이미 정해진 결과를 받아서 출력만 해야하지않을까?

2022-04-19 14:39 UTC, ghost commented on src/main/java/model/Validator.java
> +        return names.length >= 2;
숫자는 상수로 선언해줘서 값의 의미를 명확하게 드러내자!
다른 사람은 왜 숫자 5와 2로 검증하는지 이해가 어려울 수 있어

2022-04-19 21:01 UTC, gkfla668 commented
최~~대한 피드백 반영해서 전체적으로 수정해봤어요 ! 
if-else문이 너무 많아ㅅ ㅓ .. 애먹었네요ㅕ,.,...... 코드 길이도 최대한 줄여보려.. 메서드 쪼개봤어요 
이번 미션 통해서 확실히 클래스에 대해서도 좀 더 알 것 같구 (객체 분리, 가져야 하는 type 등)
get, create 메서드명도 언제 구분해서 사용해야 하는지, 
전체적으로 mvc 패턴을 통해 어떻게 해야 코드가 깔끔해지는지 
많이 부족하지만 제대로 배우고 있는 것 같아요 감사합니다 !!! 

수정할게 많지만..! 피드백 부탁드릴게요! 감사해요 🙂

2022-04-22 06:38 UTC, gkfla668 commented
게임 결과 생성하는 클래스 테스트를 더 구체적으로 하려고 했는데,
 Line을 생성하는게 random이라 location을 알 수 없는 부분이라.. 
근데 뭔가 location을 다루는 메서드들을 테스트 해야 할 것 같긴 한데 private 메서드들은 최대한 안건드릴려고 
어차피 public 메서드가 private메서드들을 다루니까 public인 createGameResult() 메서드만 테스트 해서 사이즈만 테스트 했거든요 ㅜㅜ 피드백 부탁드립니다 ~~!

2022-04-23 14:07 UTC, gch01410 requested changes
오! 코드 더 깔끔해졌네 👍 👍 
잘하고 있어!

2022-04-23 14:07 UTC, ghost commented on src/main/java/model/Lines.java
> +    private final int height;
width, height 값을 필드로 갖지않고도 width,height값을 알 수 있지않을까?

2022-04-23 14:07 UTC, ghost commented on src/main/java/model/Ladder.java
> +    public List<Line> getLadder() {
전에 알려줬다고 생각하고 있었네 ㅎㅎ;;
한 클래스안에서 메서드 선언순서는 보통 아래 2가지 중 하나를 선택해서 사용하고 있어!

1.
생성자
static 메서드
public 메서드
private 메서드
getter 메서드

2.
생성자
static 메서드
public 메서드
위 public메서드에서 호출하는 private 메서드들
public 메서드 
위 public메서드에서 호출하는 private 메서드들
반복..
getter 메서드

2022-04-23 14:07 UTC, ghost commented on src/main/java/controller/LadderGame.java
> +            nameLength = Validator.isValidPlayerNameLength(names);
참가자 이름을 갖고 있는 Players객체가 이름에 대해 검증하는 책임을 갖는건 어떻게 생각해?

2022-04-23 14:07 UTC, ghost commented on src/main/java/controller/LadderGame.java
> +        boolean prizesCount;
변수명만 보면 prize의 개수를 갖고 있는 int형 변수로 추측되는데 boolean으로 선언되어 있어!
더 적절한 변수명으로 수정해보자!

2022-04-23 14:07 UTC, ghost commented on src/main/java/view/InputView.java
> +
사다리 높이로 입력받는 값이 정수가 아니면 에러가 발생해서 시스템이 종료되고 있어!
예외(exception)를 활용해서 시스템을 종료시키지않고 다시 입력받도록 해보자!

2022-04-23 14:07 UTC, ghost commented on src/main/java/model/Lines.java
> +        List<Integer> count;
count 변수는 선언과 초기화를 같이할 수 있어보여!

2022-04-23 14:07 UTC, ghost commented on src/main/java/model/Lines.java
> +            count = createBridgesCounts(lines, width, height);
create- 메서드는 객체를 생성해서 반환할때 사용하는데, Integer형 리스트를 반환하는건 객체를 생성해서 반환하는것과는 조금 다른것 같아.
bridge의 개수를 계산하는거니깐.. calculate- 로 시작하면 어떨까?

2022-04-23 14:07 UTC, ghost commented on src/main/java/model/Lines.java
> +    private int upDateBridgeCount(List<Boolean> points, int index, int count) {
update는 한단어로 봐도 될 것 같아!

2022-04-23 14:07 UTC, ghost commented on src/main/java/model/Lines.java
> +            }
stream을 사용해서 구현해볼 수 있을까?
그러면 로직이 더 깔끔해질 수 있어!

2022-04-23 14:07 UTC, ghost commented on src/main/java/controller/LadderGame.java
> +    }
게임결과를 출력하는 로직안에 게임결과를 어떻게 출력할지(어떤 플레이어의 결과를 출력할지)도 자연스럽게 포함되는것이 아닐까?
메서드명을 printGameResult로 해도 충분해보여!
그리고 메서드명에 And를 붙여서 여러가지 일을 하는것은 안좋아!
And를 붙일꺼면 아예 메서드를 쪼개서 메서드는 하나의 일만 하도록 분리시키는게 좋아~

2022-04-23 14:07 UTC, ghost commented on src/main/java/model/GameResultCreator.java
> +    }
players, lines는 필드로 갖고있고 prizes는 필드로 안갖도록한 이유가 있을까?

그리고 GameResultCreator가 이 필드들을 갖고 있을 필요가 있는지 고민해봐!
이 값들은 GameResultCreator에서 계속해서 사용되는 값이 아니고, 게임결과를 만들어내는데 잠깐 필요한 값이 아닐까?

2022-04-23 14:07 UTC, gch01410 commented on src/test/java/LinesTest.java
> +        }
테스트 코드를 작성할때도 private 메서드를 만들어서 메서드를 쪼갤 수 있어!
가독성 좋아지도록 변경해보자!

2022-04-25 04:14 UTC, gkfla668 commented on src/main/java/model/Lines.java
> +            count = createBridgesCounts(lines, width, height);
저도 메서드명 엄청 고민했었는데 calculate가 있었죠! 맞다 ㅎㅎ. .

2022-04-26 02:21 UTC, gkfla668 commented on src/main/java/model/GameResultCreator.java
> +    }
GameResultCreator 안에 다른 메서드들에서 사용돼서 ..! 다 없애구 매개변수로 전달하려다 너무 많아서 사용되는 두가지만 남겼었어요 ㅜㅜ 매개변수가 3개이상 사용돼서 흠 어떻게 해야할까요....

2022-04-26 03:20 UTC, gkfla668 commented on src/main/java/controller/LadderGame.java
> +            nameLength = Validator.isValidPlayerNameLength(names);
프린트문때문에 .. players가 view를 호출할수 없어서 system out print 한줄 작성해서 players가 검증하도록 했는데 맞는건가요 ?!?! . .

2022-04-27 05:04 UTC, gkfla668 commented on src/main/java/model/Ladder.java
> +    public List<Line> getLadder() {
아 저번에 알려주셨어요! 메모해놓고 1번으로 규칙 지키고 있었는데 getter때문에 그런건가요??

2022-04-27 06:13 UTC, gkfla668 commented
if나 break문 stream으로 어떻게 작성해야하는지 ㅠㅠ 검색해봐도 잘 모르겠어요 ,,,

2022-05-01 11:46 UTC, gch01410 requested changes
거의 다 왔어!
조금만 더 힘내자!

2022-05-01 11:46 UTC, gch01410 commented on src/main/java/model/Lines.java
> +            }
결국에는 count 리스트안의 값 중 0이 있는지를 확인하면 되는거니깐 이렇게 하면 되지않을까?
```java
replay = count.stream()
            .anyMatch(i -> i == 0);
```

2022-05-01 11:46 UTC, gch01410 commented on src/main/java/model/GameResultCreator.java
> +    }
위 매개변수들을 갖는 객체를 새로 만드는것도 방법이겠네!
근데 여기서는 3개여도 괜찮을 것 같아!

2022-05-01 11:46 UTC, gch01410 commented on src/test/java/PlayersTest.java
> +public class PlayersTest {
<img width="857" alt="스크린샷 2022-05-01 오후 8 43 33" src="https://user-images.githubusercontent.com/26810182/166144336-c299f215-5482-42bb-bf55-f77794e38ad4.png">

인텔리J 오른쪽 위에 방패모양 누르면 테스트 코드 실행시키고 테스트 커버리지 숫자가 나오거든?
특정 패키지, 클래스, 메서드, 라인의 테스트 커버리지를 알 수 있고, 클릭하면 어떤 메서드의 테스트 코드가 작성안되었는지도 알 수 있어!
부족한 부분 채워넣어보자!

2022-05-01 21:09 UTC, gkfla668 commented on src/test/java/PlayersTest.java
> +public class PlayersTest {
stream에 대해서 더 공부해야겠어여 ㅎㅎ ... 
테스트코드 저것도 이제 알았네용 꿀팁 !!!

2022-05-01 23:49 UTC, gch01410 approved these changes
수고했어!! 👏 👏 
3달동안 정말 고생많았어! ㅋㅋ

2022-05-01 23:49 UTC, gch01410 commented on src/main/java/model/Validator.java
> +    }
stream 👍

2022-05-01 23:49 UTC, gch01410 commented on src/main/java/view/OutputView.java
> +    }
한 줄만 반복하더라도 블록`{}`을 지정해주는게 가독성에 좋아!

2022-05-01 23:49 UTC, gch01410 commented on src/test/java/LinesTest.java
> +    void 정상적인_사다리_생성을_확인하는_경우() {
이 테스트 코드가 성공했다가 실패했다가 하고 있어
확인 한번 해줘~

2022-05-01 23:49 UTC, merged