pr요청_진희
cleancode-practice-study/java-ladder pull request #2
Opened 2022-04-19 00:47 UTC by Egenieee

사다리 타는 로직을 더 리팩토링 해볼 수 있을 것 같은데 저 로직에서 더 이상 어떻게 줄여야 하는 지 아무리 생각해도 안떠올라서.. 일단 pr 요청합니다! 출력하는 부분도 이름이랑 실행 결과 부분이 조금 밀리는 거 같긴 한데 저것도 프론트엔드 단 문제인거 같아서 신경 안썼습니다..!

항상 수고많으세요 ㅜ 감사합니다🥲🥲

2022-04-21 14:13 UTC, gch01410 requested changes
구조 엄청 깔끔한데?? 💯 💯 
다음은 테스트 코드도 작성해서 요청해줘!

2022-04-21 14:13 UTC, ghost commented on src/main/java/controller/Controller.java
> +        } else {
프로그래밍 요구사항에 `else 예약어를 쓰지 않는다` 가 있어!
else를 사용안하고 구현해보자!

2022-04-21 14:13 UTC, ghost commented on src/main/java/controller/Controller.java
> +        }
if문은 1개만 있어도 구현가능하지 않을까?

2022-04-21 14:13 UTC, ghost commented on src/main/java/domain/Line.java
> +    private final ArrayList<Boolean> points = new ArrayList<>();
java collection은 인터페이스 타입으로 선언해줘!
`이펙티브 자바 - 객체는 인터페이스를 사용해 참조하라` 구글링해서 확인해봐!

2022-04-21 14:13 UTC, ghost commented on src/main/java/domain/LadderGame.java
> +    }
👍 
stream을 이용하도록 변경해보자!

2022-04-21 14:13 UTC, ghost commented on src/main/java/controller/Controller.java
> +    }
name을 갖고 있는 Player 객체가 name값 검증에 대한 책임을 갖는건 어떻게 생각해?

2022-04-21 14:13 UTC, ghost commented on src/main/java/domain/LadderGame.java
> +        return new Outputs(outputs);
stream을 이용해볼 수 있을까?

2022-04-21 14:13 UTC, ghost commented on src/main/java/domain/Ladder.java
> +    }
이 로직도 stream을 이용해서 구현해볼 수 있을까?
IntStream에 대해서 확인해봐!

2022-04-21 14:13 UTC, ghost commented on src/main/java/domain/Ladder.java
> +        int rootCount;
선언과 초기화를 합쳐도 될 것 같아!

2022-04-21 14:13 UTC, ghost commented on src/main/java/domain/Ladder.java
> +        return output.get(currentRowLine);
필요한 Output만 받아도 되지않을까?

2022-04-21 14:13 UTC, ghost commented on src/main/java/domain/Ladder.java
> +        int lineRowLength = lines.get(0).getLine().size();
중복을 제거해보자!

2022-04-21 14:13 UTC, ghost commented on src/main/java/domain/Ladder.java
> +        }
row와 column이 서로 바뀐것 같아!
`currentRowLine != ladderWidth`, `currentRowLine != 0` 로직을 메서드로 분리하면 이 로직의 의미를 더 잘 드러낼 수 있지않을까?

2022-04-21 23:13 UTC, Egenieee commented on src/main/java/domain/Line.java
> +    private final ArrayList<Boolean> points = new ArrayList<>();
엇 이건 힌트에 나와있는대로 했어요..!! 이렇게 해야하는 건줄 알고..ㅎㅎㅎ

2022-04-21 23:40 UTC, Egenieee commented on src/main/java/controller/Controller.java
> +    }
이렇게 해보려고 했는데, 아무래도 Player 객체 후보단 생성 전에 검증 로직이 들어가는 게 더 나을거 같아서 이렇게 했습니다..ㅠ

2022-04-22 00:26 UTC, Egenieee commented on src/main/java/domain/Ladder.java
> +        int lineRowLength = lines.get(0).getLine().size();
어떤 중복을 제거해야 하는지 잘 모르겠습니다..ㅠ

2022-04-28 14:11 UTC, ghost commented on src/main/java/domain/Ladder.java
> +    int ladderWidth;
width, height는 lines로 구할 수 있는데 필드로 갖고 있어야할까?
width, height 구하는 로직의 중복제거는 메서드로 분리해도 되지않을까??

2022-04-28 14:11 UTC, ghost commented on src/main/java/domain/Ladder.java
> +        for (currentRowLine = startLine, currentColumnLine = 0 ; currentColumnLine < ladderHeight  ; ) {
currentRowLine와 currentColumnLine 의미가 서로 바뀐것 같은데?? (row : 행, column : 열)

2022-04-28 14:11 UTC, ghost commented on src/main/java/domain/RandomLadderCreator.java
> +                .forEach(i -> lines.add(new Line(new RandomLineCreator().getLine(playerCount))));
👍 
stream의 map(mapToLong, mapToObj, mapToInt ...)과 collect를 이용하도록 해보자!

2022-04-28 14:11 UTC, gch01410 commented on src/main/java/domain/LadderGame.java
> +        return Arrays.stream(names.split(",")).collect(Collectors.toList());
보통 stream을 사용할때 한 줄에 `.` 1개만 찍어!
```java
return Arrays.stream(names.split(","))
            .collect(Collectors.toList());
```

2022-04-28 14:11 UTC, ghost commented on src/main/java/domain/LadderGame.java
> +        List<String> outputs = Arrays.stream(outputNames.split(",")).collect(Collectors.toList());
👍 
한줄에 `.`하나만 찍도록 줄바꿈 해주자!

2022-04-28 14:11 UTC, ghost commented on src/main/java/controller/Controller.java
> +        printEachGameResult(gameResult, players, printCommand);
👍

2022-04-28 14:11 UTC, ghost commented on src/main/java/controller/Controller.java
> +    }
👍 👍

2022-04-28 14:11 UTC, ghost commented on src/main/java/domain/LadderGame.java
> +    }
LadderGame은 입력값을 검증하는 역할, 게임결과를 구하는 역할, 사다리생성하는 역할 등..
여러 역할을 하고 있다보니 객체가 뚱뚱해진 느낌이야! 단일책임원칙에 위반되고 있어!
역할에 따라 객체를 분리해볼 수 있을까?
LadderGame은 어느 역할들을 하면 될지 고민해보고 수정해봐!

2022-04-28 14:11 UTC, ghost commented on src/main/java/controller/Controller.java
> +    }
생성전에 검증로직이 있는게 어느점이 낫다고 생각했는지 알 수 있을끼?
정답은 없어! 그냥 궁금해서!

2022-04-28 14:35 UTC, gch01410 requested changes
잘하고 있어! 💯 
조금만 더 리팩토링해보자! 거의 다 왔다!

2022-04-28 14:35 UTC, gch01410 commented on src/main/java/domain/LadderGame.java
> +            Player player = players.getPlayers().get(columnIndex);
Players객체에서 원하는  Player만 받아올 수 있지 않을까?

2022-04-28 14:35 UTC, gch01410 commented on src/test/java/domain/GameResultTest.java
> +
💯 💯

2022-04-28 14:35 UTC, gch01410 commented on src/main/java/domain/RandomLineCreator.java
> +    private final List<Boolean> points = new ArrayList<>();
points를 필드로 선언하지 않아도 괜찮지 않을까?

2022-04-28 14:35 UTC, gch01410 commented on src/test/java/domain/LadderGameTest.java
> +public class LadderGameTest {
<img width="882" alt="스크린샷 2022-04-28 오후 11 16 03" src="https://user-images.githubusercontent.com/26810182/165775076-1e90460b-48fb-4ab6-83ba-ca4f0b651145.png">

인텔리J 오른쪽 위에 방패모양 누르면 테스트 코드 실행시키고 테스트 커버리지 숫자가 나오거든?
특정 패키지, 클래스, 메서드, 라인의 테스트 커버리지를 알 수 있어
커버리지 👍 👍

2022-04-28 14:35 UTC, gch01410 commented on src/test/java/domain/RandomLineCreatorTest.java
> +    }
https://tecoble.techcourse.co.kr/post/2020-05-17-appropriate_method_for_test_by_interface/
https://tecoble.techcourse.co.kr/post/2020-05-07-appropriate_method_for_test_by_parameter/
여기 글 읽어보고 랜덤 때문에 테스트하기 어려웠던 메서드들도 더 테스트 해보자!

2022-04-29 04:13 UTC, Egenieee commented on src/main/java/controller/Controller.java
> +    }
객체 생성 후에 검증해서 다시 객체를 만들게 되면, 메모리 면에서 효율적이지 않을 거라고 생각했습니다..!!

2022-04-29 06:42 UTC, Egenieee commented on src/main/java/domain/Ladder.java
> +        for (currentRowLine = startLine, currentColumnLine = 0 ; currentColumnLine < ladderHeight  ; ) {
맨날 헷갈리네요 이건 ㅎㅎ;;

2022-05-05 07:57 UTC, gch01410 approved these changes
3달동안 수고 많았어! 👏 👏 
머지할게~

2022-05-05 07:57 UTC, gch01410 commented on src/main/java/domain/Ladder.java
> +    }
👍 👍

2022-05-05 07:57 UTC, gch01410 commented on src/main/java/domain/Validator.java
> +public class Validator {
👍

2022-05-05 07:57 UTC, gch01410 commented on src/main/java/domain/MovableRootCreator.java
> +}
테스트 코드에서 사용할 용도로 만든 클래스는 테스트 패키지에 위치시켜도 될 것 같아!

2022-05-05 07:57 UTC, merged